
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ika
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        petugas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        noresi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nopol = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        mobil = new javax.swing.JRadioButton();
        motor = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        tglmasuk = new com.toedter.calendar.JDateChooser();
        tglkeluar = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setText("APLIKASI PARKIR");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(200, 10, 580, 90);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1310, 120);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 340, 10));

        jLabel8.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel8.setText("Data Transaksi");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        jLabel6.setText("Nama Petugas");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 30));
        jPanel3.add(petugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 170, 30));

        jLabel7.setText("No Resi");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 30));

        noresi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel3.add(noresi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 170, 30));

        jLabel5.setText("No Polisi");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 30));

        jLabel9.setText("Jenis Kendaraan");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 30));

        jLabel10.setText("Tanggal Masuk");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 110, 30));

        jLabel12.setText("Tanggal");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 110, 30));

        nopol.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel3.add(nopol, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 170, 30));

        jLabel13.setText("Tanggal Keluar");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, 30));

        buttonGroup1.add(mobil);
        mobil.setText("Mobil");
        mobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilActionPerformed(evt);
            }
        });
        jPanel3.add(mobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 80, 30));

        buttonGroup1.add(motor);
        motor.setText("Motor");
        jPanel3.add(motor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 70, 30));

        jLabel14.setText("Total Harga Penitipan");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 130, 30));

        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel3.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 100, 30));
        jPanel3.add(tglmasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 170, 30));
        jPanel3.add(tglkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 170, 30));

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 130, 340, 350);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 30));

        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel1.add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, 30));

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, 30));

        jButton5.setText("Print");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 30));

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel1.add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(350, 130, 150, 350);

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Calisto MT", 1, 18)); // NOI18N
        jLabel11.setText("Daftar Bayar");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 160, 30));

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nomor", "Nama_Petugas", "No_Resi", "No_Polisi", "Jenis_Kendaraan", "Tanggal_Masuk", "Tanggal_Keluar", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 770, 290));

        getContentPane().add(jPanel4);
        jPanel4.setBounds(510, 130, 800, 350);

        setSize(new java.awt.Dimension(1325, 524));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String TglMasuk = dateFormat.format(tglmasuk.getDate());
        String TglKeluar = dateFormat.format(tglkeluar.getDate());
        
        String JenisKendaraan = "";
        if (motor.isSelected()) {
            JenisKendaraan = "MOTOR";
        } else {
            JenisKendaraan = "MOBIL";
        }
        
        String SQL ="INSERT INTO t_member (nm_petugas,no_resi,no_pol,jk,tgl_masuk,tgl_keluar,harga)"
                + "VALUES('"
                +petugas.getText()+"','"
                +noresi.getText()+"','"
                +nopol.getText()+"','"
                +JenisKendaraan+"','"
                +TglMasuk+"','"
                +TglKeluar+"','"
                +total.getText()+"')";
        int status = KoneksiDB.execute(SQL);
        if (status == 1) {
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate","Sukses", JOptionPane.INFORMATION_MESSAGE);
            selectData();
        } else {
            JOptionPane.showMessageDialog(this, "Data gagal diupdate","Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        selectData();          // TODO add your handling code here:
    }//GEN-LAST:event_RefreshActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
         int baris = tblData.getSelectedRow();
        if (baris != -1){
            String NIS = tblData.getValueAt(baris,1).toString();
            String SQL = "DELETE FROM t_member WHERE no_resi='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
       
    }//GEN-LAST:event_DeleteActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MessageFormat header = new MessageFormat("Daftar Transaksi");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}       ");

        try {
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }catch(java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
         petugas.setText("");
        noresi.setText("");
        nopol.setText("");
        tglmasuk.setDate(null);
        tglkeluar.setDate(null);
    }//GEN-LAST:event_ClearActionPerformed

    private void mobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if(baris != -1){
            noresi.setText(tblData.getValueAt(baris, 0).toString());
            petugas.setText(tblData.getValueAt(baris, 1).toString());
            nopol.setText(tblData.getValueAt(baris, 2).toString());
            if("MOTOR".equals(tblData.getValueAt(baris, 3).toString())){
                motor.setSelected(true);
            }else{
                mobil.setSelected(true);
            }
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date Masuk = null;
            try{
                Masuk = date.parse(tblData.getValueAt(baris, 4).toString());
            }catch (ParseException ex){
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            Date Keluar = null;
            try{
                Keluar = date.parse(tblData.getValueAt(baris, 5).toString());
            }catch(ParseException ex){
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            tglmasuk.setDate(Masuk);
            tglkeluar.setDate(Keluar);
        }
    }//GEN-LAST:event_tblDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Refresh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton mobil;
    private javax.swing.JRadioButton motor;
    private javax.swing.JTextField nopol;
    private javax.swing.JTextField noresi;
    private javax.swing.JTextField petugas;
    private javax.swing.JTable tblData;
    private com.toedter.calendar.JDateChooser tglkeluar;
    private com.toedter.calendar.JDateChooser tglmasuk;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"Nama Petugas","No Resi","NOPOL","Jenis Kendaraan","Tgl Masuk","Tgl Keluar","Harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_member";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        
        try{
            while(rs.next()){
                String NamaPetugas = rs.getString(1);
                String NoResi = rs.getString(2);
                String NoPol = rs.getString(3);
                String JenisKendaraan = "";
                if("MOBIL".equals(rs.getString(4))){
                    JenisKendaraan = "MOBIL";
                }else {
                    JenisKendaraan = "MOTOR";
                }
                String TanggalMasuk = rs.getString(5);
                String TanggalKeluar = rs.getString(6);
                String Harga = rs.getString(7);
                String data[] = {NamaPetugas,NoResi,NoPol,JenisKendaraan,TanggalMasuk,TanggalKeluar,Harga};
                dtm.addRow(data);
            }
        }catch (SQLException ex){
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblData.setModel(dtm);//To change body of generated methods, choose Tools | Templates.
    }
    }

